// ui_defs.h
#ifndef UI_DEFS_H
#define UI_DEFS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "stdint.h"

/*
 * UI_MAX_CHILDREN, UI_MAX_STRING_LENGTH, UI_MAX_ID_LENGTH, UI_MAX_ICON_STATES
 * are defined in ui_config.h, which is auto-generated by figma2lvgl from the
 * parsed XML. This keeps the values always in sync with the actual design.
 *
 * NOTE: ui_style.c (in priv_src/) also includes ui_defs.h. Ensure
 * priv_include/ is on the include path for all source files in ui_src/,
 * not just the generated screen files.
 *   ESP-IDF / Zephyr : handled automatically by component include dirs.
 *   Bare-metal Makefile: add -Iui_src/priv_include to CFLAGS.
 */
#include "ui_config.h"


typedef struct {
    bool        has_bg;
    uint32_t    bg;              // raw hex e.g. 0xFFFFFF
    bool        has_bg_opa;
    uint8_t     bg_opa;
    bool        has_border_color;
    uint32_t    border_color;    // raw hex
    bool        has_border_width;
    lv_coord_t  border_width;
    bool        has_radius;
    lv_coord_t  radius;
} ui_style_box_t;

typedef struct {
    bool        has_color;
    uint32_t    color;           // raw hex
    bool        has_size;
    uint16_t    size;
    bool        has_align;
    lv_text_align_t align;
} ui_style_text_t;

typedef struct {
    bool        has_opacity;
    uint8_t     opacity;
} ui_style_effects_t;


typedef struct {
    ui_style_box_t      box;
    ui_style_text_t     text;
    ui_style_effects_t  effects;
} ui_style_t;


typedef enum
{
    UI_CHILD_LABEL,
    UI_CHILD_BAR,
    UI_CHILD_IMAGE,

} ui_child_type_t;

// Multi-state icon description
typedef struct {
    uint8_t total_states;
    const void* state_src[UI_MAX_ICON_STATES];   // pointer to arrays OR file paths
} ui_icon_t;

typedef struct {

    ui_child_type_t type;
    char id[UI_MAX_ID_LENGTH];

    lv_obj_t *lv_obj;

    int x;
    int y;
    int w;
    int h;
    ui_style_t style;       // ← add this, zero-initialized = "no styles"
    union {

        struct {    // LABEL
            char text[UI_MAX_STRING_LENGTH];
        } label;

        struct {    // BAR
            int32_t value;
            //int32_t min;
            //int32_t max;
        } bar;

        struct {
            const lv_image_dsc_t *src;
        } image;


    } data;

} ui_child_t;
// A complete screen
typedef struct {
    const char *name;
    ui_child_t children[UI_MAX_CHILDREN];
    uint8_t child_count;

    lv_obj_t *lv_screen;     // created at runtime
} ui_screen_t;





#ifdef __cplusplus
}
#endif


#endif