# config_writer.py
#
# Auto-generates ui_config.h from parsed screen data.
# All constants that the generated C depends on are written here so that
# ui_defs.h stays stable and UI_MAX_CHILDREN is always exactly what the
# project requires — no hardcoding, no cap, no user action needed.

from pathlib import Path


def write_ui_config(screens, out_dir: Path):
    """
    Compute UI_MAX_CHILDREN from the parsed screens and write ui_config.h.

    Parameters
    ----------
    screens  : list of ParsedScreen
    out_dir  : destination directory (priv_include/)

    Returns
    -------
    (max_children, largest_screen_name)
    """
    if not screens:
        max_children  = 1
        largest_name  = "none"
    else:
        largest       = max(screens, key=lambda s: len(s.children))
        max_children  = max(len(largest.children), 1)
        largest_name  = largest.name

    config_path = out_dir / "ui_config.h"
    with open(config_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by figma2lvgl — do not edit */\n")
        f.write(f"/* Largest screen: {largest_name} "
                f"({max_children} children) */\n\n")
        f.write(f"#define UI_MAX_CHILDREN      {max_children}\n")
        f.write(f"#define UI_MAX_STRING_LENGTH 30\n")
        f.write(f"#define UI_MAX_ID_LENGTH     30\n")
        f.write(f"#define UI_MAX_ICON_STATES   8\n")

    return max_children, largest_name
