# config_writer.py
#
# Auto-generates ui_config.h from parsed screen data.
# All constants that the generated C depends on are written here so that
# ui_defs.h stays stable and UI_MAX_CHILDREN is always exactly what the
# project requires — no hardcoding, no cap, no user action needed.

from pathlib import Path


def write_ui_config(screens, out_dir: Path):
    """
    Write ui_config.h into out_dir with the constants all generated screen
    files depend on: UI_MAX_STRING_LENGTH, UI_MAX_ID_LENGTH, UI_MAX_ICON_STATES.

    There is no UI_MAX_CHILDREN — the per-screen struct is always exactly
    the right size for the design.

    Parameters
    ----------
    screens  : list of ParsedScreen
    out_dir  : destination directory (priv_include/)
    """
    largest_name = max(screens, key=lambda s: len(s.children)).name if screens else "none"

    config_path = out_dir / "ui_config.h"
    with open(config_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by figma2lvgl — do not edit */\n")
        f.write(f"/* Generated from: {largest_name} */\n\n")
        f.write(f"#define UI_MAX_STRING_LENGTH 30\n")
        f.write(f"#define UI_MAX_ID_LENGTH     30\n")
        f.write(f"#define UI_MAX_ICON_STATES   8\n")

    return largest_name
